channels:
  - conda-forge
  - ome
dependencies:
  - python==3.9.*
  - distributed==2022.2.0
  - pip
  - pip:
    - omero-py==5.19.2
    - scikit-image==0.22.0
    - pandas==2.2.2
    - jupyter==1.0.0
    - ome-zarr==0.8.3
    - dask-image==2023.8.1
    - stardist==0.8.5
    # dependency used to convert the OMERO masks into numpy array
    - omero-cli-zarr==0.5.5
    # dependency to save the labels as geojson file
    - geojson==3.1.0
    - tensorflow-macos==2.12.0; platform_system == "Darwin"
    - tensorflow==2.12.0; platform_system != "Darwin"
