channels:
  - conda-forge
  - ome
dependencies:
  - python==3.9.*
  - ome::zeroc-ice36-python==3.6.5
  - distributed==2022.2.0
  - pip
  - pip:
    - pooch==1.8.1
    - omero-py==5.19.2
    - scikit-image==0.22.0
    - pandas==2.2.2
    - jupyter==1.0.0
    - ome-zarr==0.8.3
    - dask-image==2023.8.1
    - stardist==0.8.5
    # dependency used to convert the OMERO masks into numpy array
    - omero-cli-zarr==0.5.5
